# Generated by Django 3.1.2 on 2020-10-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('health_insurance', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('income', models.IntegerField()),
                ('home_status', models.CharField(max_length=20)),
                ('home_owner', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=20)),
                ('deceased_parent_name', models.CharField(max_length=20)),
                ('cause_of_death', models.CharField(max_length=20)),
                ('sponsor_name', models.CharField(max_length=20)),
                ('family_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('birthdate', models.DateField()),
                ('hobbies', models.CharField(max_length=20)),
                ('education_status', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=20)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.family')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price_unit', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=20)),
                ('grade_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=20)),
                ('success', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('orphan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.orphan')),
            ],
        ),
        migrations.CreateModel(
            name='family_subsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.family')),
                ('subsidy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.subsidy')),
            ],
        ),
    ]
