# Generated by Django 3.1.2 on 2020-10-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_subsidy',
            name='sub_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='cause_of_death',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='deceased_parent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='health_insurance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='health_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='home_owner',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='family',
            name='job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='sponsor_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='health_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='hobbies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orphaneducation',
            name='grade_year',
            field=models.CharField(choices=[('PRE', 'Preschool'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'SIXth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelfth'), ('13', 'Thirteenth'), ('UNI', 'University')], default='PRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='age_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='age_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='price_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
