# Generated by Django 3.1.2 on 2020-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0004_auto_20201022_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
