# Generated by Django 3.1.2 on 2020-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0005_auto_20201022_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
