# Generated by Django 3.1.2 on 2020-10-22 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0006_auto_20201022_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orphaneducation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='orphaneducation',
            name='updated',
        ),
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='family_subsidy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family_subsidy',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='family_subsidy',
            name='updated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='family_subsidy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orphan',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='score_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='score_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='score_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='score_final',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidy',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='family_subsidy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orphaneducation',
            name='grade_year',
            field=models.CharField(choices=[('PRE', 'Preschool'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'SIXth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelfth'), ('13', 'Thirteenth'), ('UNI', 'University')], default='PRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='orphaneducation',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
