# Generated by Django 3.1.2 on 2020-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0007_auto_20201022_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_subsidy',
            name='updated',
        ),
        migrations.AddField(
            model_name='orphaneducation',
            name='updated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
