# Generated by Django 3.1.2 on 2020-10-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0008_auto_20201024_1109'),
        ('Mvpapp', '0008_auto_20201022_1645'),
    ]

    operations = [
    ]
