# Generated by Django 3.1.2 on 2020-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0009_merge_20201024_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='sponsor_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
