# Generated by Django 3.1.2 on 2020-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0011_auto_20201024_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphaneducation',
            name='success',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
