# Generated by Django 3.1.2 on 2020-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0012_auto_20201024_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphaneducation',
            name='orphan_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.orphan'),
        ),
    ]
