# Generated by Django 3.1.2 on 2020-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0013_auto_20201025_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphaneducation',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
