# Generated by Django 3.1.2 on 2020-10-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0019_auto_20201025_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='age_max',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='age_min',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
