# Generated by Django 3.1.2 on 2020-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0020_auto_20201025_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphaneducation',
            name='academic_year',
            field=models.CharField(default='2020', max_length=5, unique=True),
        ),
    ]
