# Generated by Django 3.1.2 on 2020-10-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0021_orphaneducation_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphaneducation',
            name='orphan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mvpapp.orphan'),
        ),
        migrations.AlterUniqueTogether(
            name='orphaneducation',
            unique_together={('orphan_id', 'academic_year')},
        ),
    ]
