# Generated by Django 3.1.2 on 2020-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0022_auto_20201026_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphaneducation',
            name='academic_year',
            field=models.CharField(max_length=5),
        ),
    ]
