# Generated by Django 3.1.2 on 2020-10-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0023_auto_20201026_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orphaneducation',
            unique_together={('orphan_id', 'academic_year', 'grade_year')},
        ),
    ]
