# Generated by Django 3.1.2 on 2020-10-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0024_auto_20201026_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orphaneducation',
            unique_together={('academic_year', 'grade_year')},
        ),
    ]
