# Generated by Django 3.1.2 on 2020-10-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0025_auto_20201026_1034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orphaneducation',
            unique_together={('grade_year', 'academic_year')},
        ),
    ]
