# Generated by Django 3.1.2 on 2020-10-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0026_auto_20201026_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orphaneducation',
            unique_together={('orphan_id', 'academic_year')},
        ),
    ]
