# Generated by Django 3.1.2 on 2020-10-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0030_auto_20201026_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_subsidy',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familySubsidy', to='Mvpapp.family'),
        ),
        migrations.AlterField(
            model_name='family_subsidy',
            name='subsidy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiesForFamilies', to='Mvpapp.subsidy'),
        ),
    ]
