# Generated by Django 3.1.2 on 2020-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvpapp', '0031_auto_20201026_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
